project:
  type: website
  output-dir: docs
website:
  title: "Theory Threads and Dev Doodles"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Harsh5harma
      - icon: twitter
        href: https://twitter.com/HowdySharma
format:
  html:
    theme: slate
    css: styles.css



