project:
  type: website
  output-dir: docs
website:
  title: "Theory Threads and Dev Doodles"
  google-analytics: "G-493N2M31QW"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Harsh5harma
      - icon: twitter
        href: https://twitter.com/HowdySharma
format:
  html:
    theme:
      light: journal
      dark: slate
    css: styles.css



